empid=int(input('Enter employee ID:'))
empname=(input('Enter employee Name:'))
empsal=float(input('Enter employee salary:'))
empadd=(input('Enter employee Address'))
empmarriedornot=bool(int(input('Enter employee Marred[0|1]:')))

print('Employee ID',empid)
print('Employee Name',empname)
print('Employee salary',empsal)
print('Employee Address',empadd)
print('Employee marriedornot',empmarriedornot)